routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function () {
        // dashboard
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard.index');

        //permissions
        Route::resource('/permission', 'Admin\PermissionsController', [
            'except' => ['show', 'create', 'edit', 'update', 'delete'], 'as' => 'admin'
        ]);

        //roles
        Route::resource('/role', 'Admin\RoleController', [
            'except' => ['show'], 'as' => 'admin'
        ]);

        //users
        Route::resource('/user', 'Admin\UserController', [
            'except' => ['show'], 'as' => 'admin'
        ]);

        //users
        Route::resource('/kader', 'Admin\KaderController', [
            'as' => 'admin'
        ]);
    });
});

app/Kader.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kader extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/KaderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Kader;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class KaderController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:kader.index|kader.create|kader.edit|kader.delete|kader.show']);
    }

    public function index()
    {
        $kaders = Kader::latest()->when(request()->q, function ($kaders) {
            $kaders = $kaders->where('nama_lengkap', 'like', '%' . request()->q . '%');
        })->paginate(10);

        return view('admin.kader.index', compact('kaders'));
    }

    public function show(Kader $kader)
    {
        return view('admin.kader.show', compact('kader'));
    }

    public function create()
    {
        return view('admin.kader.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_lengkap'          => 'required',
            'nama_panggilan'        => 'required',
            'angkatan'              => 'required',
            'program_studi'         => 'required',
            'semester'              => 'required',
            'kelas'                 => 'required',
            'photo'                 => 'required|image|mimes:jpeg,jpg,png|max:2000',
            'tempat_tanggal_lahir'  => 'required',
            'alamat_asal'           => 'required',
            'alamat_sekarang'       => 'required',
            'murobi_id'             => 'nullable',
        ]);

        // dd($request->all());

        // upload photo
        $photo = $request->file('photo');
        $photo->storeAs('public/kaders', $photo->hashName());

        $kaders = Kader::create([
            'nama_lengkap'          => $request->input("nama_lengkap"),
            'nama_panggilan'        => $request->input("nama_panggilan"),
            'angkatan'              => $request->input("angkatan"),
            'program_studi'         => $request->input("program_studi"),
            'semester'              => $request->input("semester"),
            'kelas'                 => $request->input("kelas"),
            'photo'                 => $photo->hashName(),
            'tempat_tanggal_lahir'  => $request->input("tempat_tanggal_lahir"),
            'alamat_asal'           => $request->input("alamat_asal"),
            'alamat_sekarang'       => $request->input("alamat_sekarang"),
            'murobi_id'             => $request->input("murobi_id"),
        ]);

        if ($kaders) {
            return redirect()->route('admin.kader.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            return redirect()->route('admin.kader.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    public function edit(Kader $kader)
    {
        return view('admin.kader.edit', compact('kader'));
    }

    public function update(Request $request, Kader $kader)
    {
        // dd($request->all());

        $this->validate($request, [
            'nama_lengkap'          => 'required',
            'nama_panggilan'        => 'required',
            'angkatan'              => 'required',
            'program_studi'         => 'required',
            'semester'              => 'required',
            'kelas'                 => 'required',
            'photo'                 => 'image|mimes:jpeg,jpg,png|max:2000',
            'tempat_tanggal_lahir'  => 'required',
            'alamat_asal'           => 'required',
            'alamat_sekarang'       => 'required',
            'murobi_id'             => 'nullable',
        ]);


        if ($request->file('photo') == "") {
            $kader = Kader::findOrfail($kader->id);
            $kader->update([
                'nama_lengkap'          => $request->input("nama_lengkap"),
                'nama_panggilan'        => $request->input("nama_panggilan"),
                'angkatan'              => $request->input("angkatan"),
                'program_studi'         => $request->input("program_studi"),
                'semester'              => $request->input("semester"),
                'kelas'                 => $request->input("kelas"),
                'tempat_tanggal_lahir'  => $request->input("tempat_tanggal_lahir"),
                'alamat_asal'           => $request->input("alamat_asal"),
                'alamat_sekarang'       => $request->input("alamat_sekarang"),
                'murobi_id'             => $request->input("murobi_id"),
            ]);
        } else {
            // Remove Image
            Storage::disk('local')->delete('public/kaders/' . $kader->photo);

            // Upload New Image
            $photo = $request->file('photo');
            $photo->storeAs('public/kaders', $photo->hashName());

            $kader = Kader::findOrFail($kader->id);
            $kader->update([
                'nama_lengkap'          => $request->input("nama_lengkap"),
                'nama_panggilan'        => $request->input("nama_panggilan"),
                'angkatan'              => $request->input("angkatan"),
                'program_studi'         => $request->input("program_studi"),
                'semester'              => $request->input("semester"),
                'kelas'                 => $request->input("kelas"),
                'photo'                 => $photo->hashName(),
                'tempat_tanggal_lahir'  => $request->input("tempat_tanggal_lahir"),
                'alamat_asal'           => $request->input("alamat_asal"),
                'alamat_sekarang'       => $request->input("alamat_sekarang"),
                'murobi_id'             => $request->input("murobi_id"),
            ]);
        }

        if ($kader) {
            return redirect()->route('admin.kader.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            return redirect()->route('admin.kader.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    public function destroy($id)
    {
        $kaders = Kader::findOrFail($id);
        $photo = Storage::disk('local')->delete('public/kaders/' . $kaders->photo);
        $kaders->delete();

        if ($kaders) {
            return response()->json([
                'status' => 'success'
            ]);
        } else {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

resources/views/admin/kader/create.blade.php
@extends('layouts.app')
@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Tambah Kader</h1>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-header">
                    <h4><i class="fas fa-user-circle"></i> Tambah Kader</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.kader.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NAMA LENGKAP</label>
                                    <input type="text" name="nama_lengkap" value="{{ old('nama_lengkap') }}"
                                    placeholder="Masukkan Nama Lengkap" class="form-control 
                                    @error('nama_lengkap') is-invalid @enderror">

                                    @error('nama_lengkap')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NAMA PANGGILAN</label>
                                    <input type="text" name="nama_panggilan" value="{{ old('nama_panggilan') }}"
                                    placeholder="Masukkan Nama Panggilan" class="form-control
                                    @error('nama_panggilan') is-invalid @enderror">

                                    @error('nama_panggilan')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ANGKATAN</label>
                                    <input type="text" name="angkatan" value="{{ old('angkatan') }}"
                                    class="form-control @error('angkatan') is-invalid @enderror">

                                    
                                    @error('angkatan')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>PROGRAM STUDI</label>
                                    <input type="text" name="program_studi" value="{{ old('program_studi') }}"
                                    class="form-control @error('program_studi') is-invalid @enderror">
                                    
                                    @error('program_studi')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>SEMESTER</label>
                                    <input type="text" name="semester" value="{{ old('semester') }}"
                                    class="form-control @error('semester') is-invalid @enderror">

                                    
                                    @error('semester')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>KELAS</label>
                                    <input type="text" name="kelas" value="{{ old('kelas') }}"
                                    class="form-control @error('kelas') is-invalid @enderror">
                                    
                                    @error('kelas')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>PHOTO</label>
                                    <input type="file" name="photo" value="{{ old('photo') }}"
                                    class="form-control @error('photo') is-invalid @enderror">

                                    
                                    @error('photo')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>TTL</label>
                                    <input type="text" name="tempat_tanggal_lahir" value="{{ old('tempat_tanggal_lahir') }}"
                                    class="form-control @error('tempat_tanggal_lahir') is-invalid @enderror">
                                    
                                    @error('tempat_tanggal_lahir')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ALAMAT ASAL</label>
                                    <textarea class="form-control @error('alamat_asal') is-invalid @enderror" 
                                    name="alamat_asal" cols="50" rows="50">{{ old('alamat_asal') }}</textarea>
                                    
                                    @error('alamat_asal')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ALAMAT SEKARANG</label>
                                    <textarea class="form-control @error('alamat_sekarang') is-invalid @enderror" 
                                    name="alamat_sekarang" cols="50" rows="50">{{ old('alamat_sekarang') }}</textarea>
                                    
                                    @error('alamat_sekarang')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">MUROBI</label>
                            <br>
                            <select class="form-control" name="murobi_id">
                                <option>-- PILIH --</option>
                                <option value={{ 3 }}>Akromi Arya</option>
                                <option value={{ 2 }}>Muhammad Kuswari</option>
                                <option value={{ 1 }}>Aljihad</option>
                            </select>
                        </div>
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>
                            SIMPAN</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i> RESET</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/admin/kader/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Edit Kader</h1>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-header">
                    <h4><i class="fas fa-user-circle"></i> Edit Kader</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.kader.update',$kader->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NAMA LENGKAP</label>
                                    <input type="text" name="nama_lengkap" value="{{ old('nama_lengkap',$kader->nama_lengkap) }}"
                                    placeholder="Masukkan Nama Lengkap" class="form-control 
                                    @error('nama_lengkap') is-invalid @enderror">

                                    @error('nama_lengkap')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NAMA PANGGILAN</label>
                                    <input type="text" name="nama_panggilan" value="{{ old('nama_panggilan',$kader->nama_panggilan) }}"
                                    placeholder="Masukkan Nama Panggilan" class="form-control
                                    @error('nama_panggilan') is-invalid @enderror">

                                    @error('nama_panggilan')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ANGKATAN</label>
                                    <input type="text" name="angkatan" value="{{ old('angkatan',$kader->angkatan) }}"
                                    class="form-control @error('angkatan') is-invalid @enderror">

                                    
                                    @error('angkatan')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>PROGRAM STUDI</label>
                                    <input type="text" name="program_studi" value="{{ old('program_studi',$kader->program_studi) }}"
                                    class="form-control @error('program_studi') is-invalid @enderror">
                                    
                                    @error('program_studi')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>SEMESTER</label>
                                    <input type="text" name="semester" value="{{ old('semester',$kader->semester) }}"
                                    class="form-control @error('semester') is-invalid @enderror">

                                    
                                    @error('semester')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>KELAS</label>
                                    <input type="text" name="kelas" value="{{ old('kelas',$kader->kelas) }}"
                                    class="form-control @error('kelas') is-invalid @enderror">
                                    
                                    @error('kelas')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>PHOTO</label>
                                    <input type="file" name="photo" value="{{ old('photo') }}"
                                    class="form-control @error('photo') is-invalid @enderror">

                                    
                                    @error('photo')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>TTL</label>
                                    <input type="text" name="tempat_tanggal_lahir" value="{{ old('tempat_tanggal_lahir',$kader->tempat_tanggal_lahir) }}"
                                    class="form-control @error('tempat_tanggal_lahir') is-invalid @enderror">
                                    
                                    @error('tempat_tanggal_lahir')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ALAMAT ASAL</label>
                                    <textarea class="form-control @error('alamat_asal') is-invalid @enderror" 
                                    name="alamat_asal" cols="50" rows="50">{{ old('alamat_asal',$kader->alamat_asal) }}</textarea>
                                    
                                    @error('alamat_asal')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>ALAMAT SEKARANG</label>
                                    <textarea class="form-control @error('alamat_sekarang') is-invalid @enderror" 
                                    name="alamat_sekarang" cols="50" rows="50">{{ old('alamat_sekarang',$kader->alamat_sekarang) }}</textarea>
                                    
                                    @error('alamat_sekarang')
                                    <div class="invalid-feedback" style="display:block">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">MUROBI</label>
                            <br>
                            <select class="form-control" name="murobi_id">
                                <option>-- PILIH --</option>
                                <option value={{ 3 }}>Akromi Arya</option>
                                <option value={{ 2 }}>Muhammad Kuswari</option>
                                <option value={{ 1 }}>Aljihad</option>
                            </select>
                        </div>
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i>
                            SIMPAN</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i> RESET</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/admin/kader/show.blade.php
@extends('layouts.app')
@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Detail Kader</h1>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-header">
                    <h4><i class="fas fa-user-circle"></i> Detail Kader</h4>
                </div>
                <div class="card-body">
                    <div class="col-12 col-sm-12 col-lg-12">
                        <div class="card author-box card-primary">
                            <div class="card-body">
                                <div class="author-box-left">
                                    <img alt="image" src="{{ Storage::url('public/kaders/'.$kader->photo) }}"
                                        class="rounded-circle author-box-picture">
                                </div>
                                <div class="author-box-details">
                                    <div class="author-box-name">
                                        <a href="#">{{ $kader->nama_lengkap }}</a>
                                    </div>

                                    <div class="author-box-job">{{ $kader->nama_panggilan }}</div>
                                    <div class="text-black-50 font-weight-bold mt-3 ">Semster</div>
                                    <p>{{$kader->semester}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Angkatan</div>
                                    <p>{{$kader->angkatan}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Program Studi</div>
                                    <p>{{$kader->program_studi}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Kelas</div>
                                    <p>{{$kader->kelas}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Tempat Tanggal Lahir</div>
                                    <p>{{$kader->tempat_tanggal_lahir}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Murobbi</div>
                                    <p>-</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Alamat Asal</div>
                                    <p>{{$kader->alamat_asal}}</p>

                                    <div class="text-black-50 font-weight-bold mt-3 ">Alamat Sekarang</div>
                                    <p>{{$kader->alamat_sekarang}}</p>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
</section>
</div>
@stop